import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { copyFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const buildDir = "./" //"D:/ObiVault/.obsidian/plugins/build/";
const assetsToCopy = ["manifest.json", "styles.css"];

async function copyAssets() {
	await mkdir(buildDir, { recursive: true });
	await Promise.all(
		assetsToCopy.map(async (file) => {
			const src = file;
			const dest = join(buildDir, file);
			await copyFile(src, dest);
		})
	);
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: buildDir + "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	//await copyAssets();
	process.exit(0);
} else {
	await context.watch();
	//await copyAssets();
}
